name: CI
# run-name: ${{ github.actor }} is learning GitHub Actions

on: push

jobs:
  test_one:
    strategy:
      fail-fast: false
      matrix:
      ruby: 2.4.9

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - run: bundle exec rake
